Dev
DihtGameDev/diht_team_10 pull request #2
Opened 2020-04-22 18:59 UTC by jux7ent

2020-04-22 22:51 UTC, chav0 requested changes

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
Так делать не очень круто, во-первых, имена захардкожены, во-вторых, что Find, что GetComponent -- не самые быстрые штуки. Все эти поля лучше сериализовать. Попробуй тут использовать обобщения, наверно...

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UIGame.cs
> +        GameManager.GAME_MANAGER.StartCoroutine(ClearChat());
А почему здесь GameManager.GAME_MANAGER?

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Study/UIMessage.cs
> +public class UIMessage : MonoBehaviour {
Очень странный код... Он же нигде не используется?

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Study/UIMessage.cs
> +public class UIMessage : MonoBehaviour {
Под UIMessage имелось в виду, что он сообщает из вьюхи в модель, что произошло нажатие на кнопку. Т.е. например в UIMessage сеттится тик, в который нажата кнопка, и дальше ты проверяешь, если UIMessage говорит тебе, что кнопка нажата, то выполняешь что-то... Типа того. Короче, если будут вопросы, обращайся)

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Study/UIMessage.cs
> +        if (Input.GetMouseButtonDown(0) && EventSystem.current.currentSelectedGameObject == someButton.gameObject) {
В UI это не используется. someButton.onClick.AddListener(OnButtonClick); - вотэта используется)

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Player/Seeker.cs
> +    private Animator _animator;
У тебя что-то везде разный код стайл. Попробуй как-нибудь к одному чему-то прийти)

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Player/Seeker.cs
> +        _animator.SetBool("IsMoving", __deltaMagnitude != 0f);
Здесь лучше заранее сделать StringToHash, т.к. в апдейте это все дело вызывается...

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Player/PlayerController.cs
> +    private Joystick _moveJoystick;
В плеере точно нужен джойстик? Может, джойстик будет управлять плеером, а не будет его частью?

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/NicknameManager.cs
> +public class NicknameManager {
тут все супер

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Player/PlayerController.cs
> +    public float moveSpeed = 5f;
Такое лучше помещать в настройки игры. В задании есть пункт "Создать общих настройки игры через ScriptableObject (+1)". Вот нужно создать такую штуку и брать все оттуда.

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Launcher.cs
> +            PhotonNetwork.GameVersion = "1";
Божи, тут что-то сложное, будем считать, что ты очень умный)))

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/GameManager.cs
> +    public static GameManager GAME_MANAGER;
Ох-ох

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/Misc/Constants.cs
> +    public static class PlayerPrefs {
АААА, почему это называется PlayerPrefs? я запутолся

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/CameraController.cs
> +         transform.eulerAngles = new Vector3(46.2f, -15f, 0f);
Вотэто бы тоже в настройки игры вытащить

2020-04-22 22:51 UTC, chav0 commented on HideAndSeek/Assets/Scripts/CameraController.cs
> +        int layerMask = LayerMask.GetMask("Obstacle"); // = 1 << 9;
Можно создать енам, как вариант)

2020-04-23 05:13 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/UI/UIGame.cs
> +        GameManager.GAME_MANAGER.StartCoroutine(ClearChat());
у меня компонент GameManager один на всю игровую сцену, который всем управляет. Вот чтобы из других частей кода я мог давать команды от его имени я создал в нем public static GameManager GAME_MANAGER; и от его имени в данном месте запускаю корутину

2020-04-23 05:16 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/Player/Seeker.cs
> +    private Animator _animator;
Чем именно?) я private поля пишу с _fieldName. public поля просто fieldName. переменные созданные в коде, которые временные __fieldName

2020-04-23 05:17 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/Launcher.cs
> +            PhotonNetwork.GameVersion = "1";
)) Это я использую PUN 2 для мультиплеера

2020-04-23 05:18 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/Misc/Constants.cs
> +    public static class PlayerPrefs {
чтобы когда я пытался обратиться к этим константам, я мог написать так: Constants.PlayerPrefs.SETTINGS. т.е. константы относящиеся к PlayerPrefs.

2020-04-23 05:21 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/CameraController.cs
> +         transform.eulerAngles = new Vector3(46.2f, -15f, 0f);
вообще это наверное в константы надо запихнуть, т.к. они будут одни и те же для всех. И там, в коде, на том месте, я подбираю, чтобы было как можно лучше

2020-04-23 05:22 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
Да, я видел что они медленные, но этот код запускается один раз при старте только. Поэтому кажется что особо нет разницы.

2020-04-23 05:26 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
А то что захардкожено, это да, плохо. Но что-то я не знаю как это обойти(если только в едиторе это проставлять(но там и код придется переписывать, т.к. UILauncher не наследует MonoBehaviour(я так и не хотел)

2020-04-23 05:27 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/CameraController.cs
> +        int layerMask = LayerMask.GetMask("Obstacle"); // = 1 << 9;
с Layer'ами? просто тут только один слой наверн будет использоваться. Хотя для чистоты и понятности кода, наверное следует создать где-нибудь enum

2020-04-23 05:39 UTC, jux7ent commented on HideAndSeek/Assets/Scripts/Player/PlayerController.cs
> +    private Joystick _moveJoystick;
вообще это контроллер игрока, который потом наследует сам игрок(например, Seeker)

2020-04-23 07:23 UTC, chav0 commented on HideAndSeek/Assets/Scripts/CameraController.cs
> +         transform.eulerAngles = new Vector3(46.2f, -15f, 0f);
Все же настройки лучше делать через ScriptableObject, как писалось в задании. Потому что настраивать что-то через код -- не самое удобное занятие, т.к. это пришлось бы перекомпилить, а скриптаблы можно прямо в рантайме править.

2020-04-23 07:28 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
public abstract class UIBase<TWidget> where TWidget : MonoBehaviour
{
    protected TWidget _widget;

    protected UIBase(TWidget widget)
    {
        _widget = widget;
    }
}

2020-04-23 07:28 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
`public abstract class UIBase<TWidget> where TWidget : MonoBehaviour
{
    protected TWidget _widget;

    protected UIBase(TWidget widget)
    {
        _widget = widget;
    }
}`

2020-04-23 07:29 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
` public abstract class UIBase<TWidget> where TWidget : MonoBehaviour
{
    protected TWidget _widget;

    protected UIBase(TWidget widget)
    {
        _widget = widget;
    }
} `

2020-04-23 07:29 UTC, chav0 commented on HideAndSeek/Assets/Scripts/UI/UILauncher.cs
> +        nicknameField = canvasGO.transform.Find("NicknameField").GetComponent<InputField>();
`
using UnityEngine;

public abstract class UIBase<TWidget> where TWidget : MonoBehaviour
{
    protected TWidget _widget;

    protected UIBase(TWidget widget)
    {
        _widget = widget;
    }
}
`

2020-04-23 22:31 UTC, merged